version: "3.1"

pipeline:
  - name: WhitespaceTokenizer
  - name: LanguageModelFeaturizer
    model_name: "bert"
    model_weights: "bert-base-multilingual-cased"
  - name: RegexFeaturizer
  - name: DIETClassifier
    epochs: 100
